baseURL = "https://meinto.github.io/"
copyright = "© Tobias Meinhardt {year}"
languageCode = "de-DE
title = "Tobias Meinhardt"
theme = "meinto"

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "rss"